### ISSUE TITLE
Sites web blocking

### ISSUE THREAD

**Issue by eric13500** [schmich/marinara#269] opened 2019-04-18 11:10 UTC
Hi.

The "Tomato Timer" Google extension allows the blocking of disruptive sites during work periods (Facebook, Twitter, etc.) by listing them separated by commas (facebook.com, twitter.com).

This option is very useful, and it would be very interesting that Marinara proposes it too.

Thanks.
Regards.

**Comment by schmich** [comment] 2019-06-11 03:14
Thanks for the feedback. This is a duplicate of issue #32. I'm tracking all feedback there, and I've added your comments to the list. This is highly requested, so it will happen, I just have to find time for it and prioritize it alongside other features.

**Closed by schmich** 2019-06-11 03:14 UTC
