### ISSUE TITLE
Naming or set label for activity

### ISSUE THREAD

**Issue by ooghry** [schmich/marinara#168] opened 2018-02-05 22:17 UTC
Hi
It would be nice if we can naming or set label for activity and apply that label in history report.
Thanks

**Comment by schmich** [comment] 2018-02-05 22:40
Thanks for the feedback. I'm closing this as a duplicate of #149. I don't have immediate plans for this feature, but a number of people have requested it, so I am absolutely considering it.

**Closed by schmich** 2018-02-05 22:40 UTC
