### ISSUE TITLE
Updating any of the options under settings stops the timer

### ISSUE THREAD

**Issue by abrarShariar** [schmich/marinara#195] opened 2018-08-15 05:54 UTC

**Comment by abrarShariar** [comment] 2018-08-19 05:50
Not really sure if this is the intended behavior, can anyone clarify?

**Comment by schmich** [comment] 2018-11-27 23:33
Closing as a duplicate of #12.

Changing any settings impacts how the timers, events, sounds, etc. work, It would be significant effort to support on-the-fly settings updates without stopping the current session (at least enough effort that I think would be better spent elsewhere).

This problem is addressed in another branch. Instead of just stopping the current session, a small dialog will popup when a user changes their settings:

![image](https://user-images.githubusercontent.com/1562839/49118484-421ce080-f259-11e8-9c99-d8039cff6480.png)

**Closed by schmich** 2018-11-27 23:33 UTC
