### ISSUE TITLE
Completed Today - incorrect display of circles

### ISSUE THREAD

**Issue by demetrous** [schmich/marinara#130] opened 2017-11-03 18:09 UTC
html of "circles":
⬤ ⬤ ⬤ ⬤
Completed Today

**Comment by schmich** [comment] 2017-11-03 18:32
Sorry, I'm not sure I understand what the issue is. Those circles are supposed to represent tomatoes (pomodoros), the individual sessions you've completed today.

How are you expecting them to appear? If they look wrong, can you include a screenshot?

**Comment by demetrous** [comment] 2017-11-03 22:35
No worries, that doesn't bother me a lot)

It appears only on my PC in Chrome, laptop works fine with nice circles,
please take a look a the screenshot:

[image: Inline image 2]

**Comment by schmich** [comment] 2017-11-03 23:11
It doesn't look like your image was uploaded to GitHub (maybe it doesn't work over email...), so I can't see the problem.

If it looks strange, it might be a font issue. I will look into it. What language/locale do you run Chrome under? Is it en-US or something different?

**Comment by demetrous** [comment] 2017-11-04 07:40
Please see an attachment.

Something wrong with a font, empty squares instead of filled circles.

Yes, I’m using en-US setting.

**Comment by schmich** [comment] 2017-11-12 04:36
Fixed with an icon font. This will be in the next release. Thanks for the feedback.

**Closed** 2017-11-12 04:35 UTC

**Comment by demetrous** [comment] 2017-11-13 00:13
Thank you for an update!

Dmitrii
